import { motion } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Download, Share2, ShoppingCart, Bot } from "lucide-react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { AnimatedCard } from "./ui/AnimatedCard";
import {
  FormData,
  Material,
  EstimateData,
  formatCurrency,
  formatCurrencyCompact
} from "@/types/predictor-form";

/* ---------------------------
   ResultsDashboard (with working export & share)
----------------------------*/
const ResultsDashboard = ({ estimate, formData }: { estimate: EstimateData; formData: FormData }) => {
  // Build PDF blob with updated header and footer
  async function buildPdfBlob(): Promise<Blob> {
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 40;

    // Add header with company details (centered)
    const addHeader = () => {
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      const companyName = "Vcniti Technologies Private Limited";
      const companyNameWidth = doc.getTextWidth(companyName);
      doc.text(companyName, (pageWidth - companyNameWidth) / 2, 30);
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      
      const cinText = "CIN No. – U47912KA2025PTC205758";
      const cinWidth = doc.getTextWidth(cinText);
      doc.text(cinText, (pageWidth - cinWidth) / 2, 45);
      
      const contactText = "E-Mail Id – info@vcniti.com, Website - www.vcniti.com, Phone No. –+91 9740059699";
      const contactWidth = doc.getTextWidth(contactText);
      doc.text(contactText, (pageWidth - contactWidth) / 2, 57);
      
      const officeText = "Office: 48, Church St, Haridevpur, Shanthala Nagar, Ashok Nagar, Bengaluru, Karnataka 560001";
      const officeWidth = doc.getTextWidth(officeText);
      doc.text(officeText, (pageWidth - officeWidth) / 2, 69);
      
      doc.line(margin, 75, pageWidth - margin, 75);
    };

    // Add footer
    const addFooter = (pageNumber: number, totalPages: number) => {
      const footerY = pageHeight - 30;
      doc.line(margin, footerY - 10, pageWidth - margin, footerY - 10);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text("Generated by Vcniti Technologies", margin, footerY);
      doc.text(`Page ${pageNumber} / ${totalPages}`, pageWidth - margin - 80, footerY);
    };

    addHeader();

    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const titleText = "Construction Material Estimate Report";
    const titleWidth = doc.getTextWidth(titleText);
    doc.text(titleText, (pageWidth - titleWidth) / 2, 100);
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Project Stage: ${formData.stage?.charAt(0).toUpperCase() + formData.stage?.slice(1) || 'N/A'}`, margin, 120);
    doc.text(`Building Type: ${formData.buildingType?.charAt(0).toUpperCase() + formData.buildingType?.slice(1) || 'N/A'}`, margin, 135);
    doc.text(`Total Area: ${formData.totalAreaSqft} sq ft`, margin, 150);
    doc.text(`Number of Floors: ${formData.floors}`, margin, 165);
    doc.text(`Quality Level: ${formData.quality?.charAt(0).toUpperCase() + formData.quality?.slice(1) || 'N/A'}`, margin, 180);
    doc.text(`Location: ${formData.city?.charAt(0).toUpperCase() + formData.city?.slice(1) || 'N/A'}`, margin, 195);
    doc.text(`Generated on: ${new Date().toLocaleString('en-IN')}`, margin, 210);

    // Prepare table data with proper serial numbers and fixed currency formatting
    const tableRows = estimate.materials.map((material, index) => {
      const unitCost = `Rs. ${material.priceLow.toLocaleString('en-IN')} – Rs. ${material.priceHigh.toLocaleString('en-IN')}`;
      const totalCost = ((material.priceLow + material.priceHigh) / 2) * material.qty;
      
      return [
        (index + 1).toString(),
        material.category,
        material.selectedBrand || 'Generic',
        `${material.qty} ${material.unit}`,
        unitCost,
        `Rs. ${totalCost.toLocaleString('en-IN')}`
      ];
    });

    // Add materials table
    autoTable(doc, {
      startY: 230,
      margin: { top: 130, left: margin, right: margin, bottom: 60 },
      body: tableRows,
      theme: 'grid',
      styles: { 
        fontSize: 9,
        cellPadding: 6
      },
      headStyles: { 
        fillColor: [41, 128, 185],
        textColor: 255,
        fontStyle: 'bold'
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250]
      },
      head: [['S.No.', 'Material', 'Brand', 'Quantity', 'Unit Cost Range', 'Total Cost (Avg)']],
      didDrawPage: (data) => {
        const pageNumber = doc.internal.getCurrentPageInfo().pageNumber;
        const totalPages = doc.internal.getNumberOfPages();
        
        if (pageNumber > 1) {
          addHeader();
        }
      }
    });

    // Add final summary
    let finalY = (doc.lastAutoTable ? doc.lastAutoTable.finalY : 230) + 20;
    // 1. INCREASE BOX HEIGHT to fit the extra line (80 -> 100)
    const summaryHeight = 100;
    const requiredSpace = summaryHeight + 50;
    const footerHeight = 40;
    if (finalY + requiredSpace > pageHeight - footerHeight) {
      doc.addPage();
      addHeader();
      finalY = 100;
    }

    // Calculate Average
    const avgCost = (estimate.totalLow + estimate.totalHigh) / 2;

    doc.setFillColor(230, 247, 255);
    doc.rect(margin, finalY, pageWidth - 2 * margin, summaryHeight, 'F');
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Final Estimate Summary", margin + 10, finalY + 25);
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Total Materials: ${estimate.materials.length} items`, margin + 10, finalY + 45);
    doc.text(`Estimated Cost Range: ${formatCurrency(estimate.totalLow)} – ${formatCurrency(estimate.totalHigh)}`, margin + 10, finalY + 60);
    doc.text(`Average Cost: Rs. ${avgCost.toLocaleString('en-IN')}`, margin + 10, finalY + 75);
    doc.text(`AI Confidence Level: ${estimate.confidence}%`, margin + 10, finalY + 90);

    // Add disclaimer
    let disclaimerY = finalY + summaryHeight + 15;
    if (disclaimerY + 30 > pageHeight - margin) { // Check if disclaimer overflows
      doc.addPage();
      addHeader();
      disclaimerY = 100; // Reset Y for new page, after header
    }
    doc.setFontSize(8);
    doc.setFont("helvetica", "italic");
    doc.text("Note: This estimate is generated using AI analysis and current market rates. Actual costs may vary based on", margin, disclaimerY + 5);
    doc.text("market conditions, supplier negotiations, and specific project requirements.", margin, disclaimerY + 17);

    // Add footer to all pages after all content is generated
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i); // Go to page i
      addFooter(i, totalPages); // Add footer with correct "Page i / N"
    }

    return doc.output("blob");
  };



  // Share (Web Share API with file when possible, fallback to copy/prompt)
  async function shareEstimate() {
    try {
      const blob = await buildPdfBlob();
      const file = new File([blob], "vcniti-construction-estimate.pdf", { type: "application/pdf" });
      const pageUrl = window.location.href;
      const shareData: CustomShareData = {
        title: "Construction Estimate",
        text: `Estimate: ${formatCurrencyCompact(estimate.totalLow)} – ${formatCurrencyCompact(estimate.totalHigh)}`,
        url: pageUrl
      };

      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      if (navigator.canShare && (navigator as any).canShare({ files: [file] })) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        await (navigator as any).share({ ...shareData, files: [file] });
        return;
      }

      if (navigator.share) {
        await navigator.share(shareData);
        return;
      }

      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(pageUrl);
        alert("Page URL copied to clipboard");
        return;
      }

      prompt("Copy this URL:", pageUrl);
    } catch (err) {
      console.error("Share failed:", err);
      alert("Share failed — fallback to copying link. See console for details.");
      if (navigator.clipboard && navigator.clipboard.writeText) {
        try {
          await navigator.clipboard.writeText(window.location.href);
          alert("URL copied to clipboard");
        } catch (copyError) { /* Intentionally ignore if clipboard write fails */ }
      } else {
        prompt("Copy this URL:", window.location.href);
      }
    }
  };

  // Download (Safari-safe)
  async function downloadEstimatePDF() {
    try {
      const blob = await buildPdfBlob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "vcniti-construction-estimate.pdf";
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Download failed:", err);
      alert("Failed to export PDF. See console for details.");
    }
  }

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen bg-gradient-to-br from-blue-50 to-purple-50 py-12 px-4"
    >
      <motion.div
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="max-w-7xl mx-auto space-y-8"
      >
        <motion.div variants={itemVariants} className="text-center space-y-4">
          <Badge variant="secondary" className="px-4 py-2">
            <Bot className="w-4 h-4 mr-2" />
            AI-Generated Estimate
          </Badge>
          <h1 className="text-4xl font-bold">Your Customized Project Estimate</h1>
          <p className="text-muted-foreground max-w-2xl mx-auto">{estimate.reasoning}</p>
        </motion.div>

        <motion.div variants={itemVariants} className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <AnimatedCard>
            <Card className="shadow-lg border-primary/20 h-full">
              <CardHeader className="text-center">
                <CardTitle className="text-lg">Total Cost Range</CardTitle>
              </CardHeader>
              <CardContent className="text-center space-y-2">
                <div className="text-2xl font-bold text-primary break-words">
                  <div>{formatCurrencyCompact(estimate.totalLow)}</div>
                  <div className="text-lg">to {formatCurrencyCompact(estimate.totalHigh)}</div>
                </div>
                <p className="text-sm text-muted-foreground">{estimate.materials.length} selected materials</p>
              </CardContent>
            </Card>
          </AnimatedCard>

          <AnimatedCard>
            <Card className="shadow-lg border-green-200 h-full">
              <CardHeader className="text-center">
                <CardTitle className="text-lg">AI Confidence</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="text-center">
                  <div className="text-3xl font-bold text-green-600">{estimate.confidence}%</div>
                </div>
                <Progress value={estimate.confidence} className="h-3" />
                <p className="text-xs text-muted-foreground text-center">Based on your selections & market data</p>
              </CardContent>
            </Card>
          </AnimatedCard>

          <AnimatedCard>
            <Card className="shadow-lg border-purple-200 h-full">
              <CardHeader className="text-center">
                <CardTitle className="text-lg">Actions</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <Button asChild variant="hero" className="w-full" size="sm">
                  <a href="https://www.vcniti.com/collections" target="_blank" rel="noopener noreferrer">
                    <ShoppingCart className="w-4 h-4 mr-2" />
                    Proceed to Purchase
                  </a>
                </Button>

                <div className="grid grid-cols-2 gap-2">
                  <Button variant="outline" size="sm" onClick={downloadEstimatePDF}>
                    <Download className="w-4 h-4 mr-1" /> Export
                  </Button>
                  <Button variant="outline" size="sm" onClick={shareEstimate}>
                    <Share2 className="w-4 h-4 mr-1" /> Share
                  </Button>
                </div>
              </CardContent>
            </Card>
          </AnimatedCard>
        </motion.div>

        <motion.div variants={itemVariants}>
          <Card className="shadow-lg">
            <CardHeader>
              <CardTitle>Selected Materials with Brands</CardTitle>
              <p className="text-sm text-muted-foreground">Your customized bill of quantities</p>
            </CardHeader>
            <CardContent>
              <div className="overflow-x-auto">
                <table className="w-full border-collapse">
                  <thead>
                    <tr className="border-b">
                      <th className="text-left p-3 font-semibold">S.No.</th>
                      <th className="text-left p-3 font-semibold">Material</th>
                      <th className="text-left p-3 font-semibold">Selected Brand</th>
                      <th className="text-left p-3 font-semibold">Quantity</th>
                      <th className="text-left p-3 font-semibold">Unit Cost</th>
                      <th className="text-left p-3 font-semibold">Total Cost</th>
                    </tr>
                  </thead>
                  <tbody>
                    {estimate.materials.map((material, index) => (
                      <tr key={material.id} className="border-b hover:bg-muted/20">
                        <td className="p-3">{index + 1}</td>
                        <td className="p-3">
                          <div>
                            <div className="font-medium">{material.category}</div>
                            {material.description && <div className="text-xs text-muted-foreground">{material.description}</div>}
                          </div>
                        </td>
                        <td className="p-3">
                          <Badge variant="secondary">{material.selectedBrand}</Badge>
                        </td>
                        <td className="p-3">
                          <span>{material.qty} {material.unit}</span>
                        </td>
                        <td className="p-3">
                          <div className="text-sm">{formatCurrencyCompact(material.priceLow)} - {formatCurrencyCompact(material.priceHigh)}</div>
                        </td>
                        <td className="p-3">
                          <div className="font-semibold text-primary">{formatCurrencyCompact(((material.priceLow + material.priceHigh) / 2) * material.qty)}</div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="border-t-2 font-bold">
                      <td colSpan={5} className="p-3 text-right">Total Estimate:</td>
                      <td className="p-3 text-primary text-lg">{formatCurrencyCompact((estimate.totalLow + estimate.totalHigh) / 2)}</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </CardContent>
          </Card>
        </motion.div>

        <motion.div variants={itemVariants} className="flex flex-col md:flex-row justify-center items-center space-y-4 md:space-y-0 md:space-x-4">
          <Button variant="outline" onClick={() => window.location.reload()} className="w-full md:w-auto">Start New Estimate</Button>
          <Button
            variant="hero"
            onClick={() => window.location.href = "https://www.vcniti.com/collections"}
            className="w-full md:w-auto"
          >
            <ShoppingCart className="w-4 h-4 mr-2" />
            Proceed to Purchase
          </Button>
        </motion.div>
      </motion.div>
    </motion.div>
  );
};

export default ResultsDashboard;